import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="px-8 mt-10">
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto lg:flex lg:flex-row lg:w-3/5 lg:h-auto">
        <img
          src="https://res.cloudinary.com/spritle/image/upload/v1655116337/cld-sample-4.jpg"
          alt="food-img"
          className="rounded-tr-md rounded-tl-md h-48 w-full lg:h-auto lg:w-2/5"
        />
        <div className="bg-white p-8 rounded-bl-md rounded-br-md">
          <h2 className="text-gray-700 font-semibold">
            shift overall look and fell by adding these wonderfull touches to
            furnitrue in your home
          </h2>
          <p className="text-sm text-gray-500 mt-4">
            Ever been in a room and gelt like something was missing? perhaps it
            felt slightly bare and univiting. ive got some simple tips to help
            you make any room feel complete.
          </p>
          <div className="flex items-center mt-8">
            <div className="flex items-center">
              <img
                src="https://res.cloudinary.com/spritle/image/upload/v1655116337/cld-sample-4.jpg"
                alt="avatar"
                className="h-10 w-10 rounded-full"
              />
            </div>
            <div className="ml-4">
              <p className="text-gray-800 text-md font-semibold">
                Michelle Appleton
              </p>
              <p className="text-gray-600 text-sm">28 Jun 2020</p>
            </div>
            <div className="w-8 h-8 ml-auto bg-gray-200 rounded-full flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="15" height="13">
                <path
                  fill="#6E8098"
                  d="M15 6.495L8.766.014V3.88H7.441C3.33 3.88 0 7.039 0 10.936v2.049l.589-.612C2.59 10.294 5.422 9.11 8.39 9.11h.375v3.867L15 6.495z"
                />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
